name: Merge Telegram TL

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"   # 每小时一次（UTC）

permissions:
  contents: write

concurrency:
  group: tl-merge
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run TL fetch & merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python fetch_and_merge_tl.py --outdir schemas

      - name: Detect changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # 把 merged.tl 复制到仓库根目录，并在根目录生成哈希（仅在变更时执行）
      - name: Copy merged.tl to repo root & build checksum (if changed)
        if: steps.diff.outputs.changed == 'true'
        run: |
          cp schemas/merged.tl ./merged.tl
          sha256sum merged.tl > merged.tl.sha256

      - name: Commit changes (if changed)
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(tl): hourly update merged.tl [skip ci]"
          git push

      - name: Compose tag & title (if changed)
        if: steps.diff.outputs.changed == 'true'
        id: tag
        run: |
          DT_UTC=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          DT_TAG=$(date -u +'%Y%m%d%H%M%S')
          SHA1=$(jq -r '.entries[0].sha' schemas/metadata.json | cut -c1-7)
          SHA2=$(jq -r '.entries[1].sha' schemas/metadata.json | cut -c1-7)
          echo "tag=tl-${DT_TAG}-${SHA1}-${SHA2}" >> $GITHUB_OUTPUT
          echo "title=TL Merge ${DT_UTC}" >> $GITHUB_OUTPUT
          {
            echo "Automated semantic merge of Telegram TL schemas."
            echo
            echo "Sources:"
            jq -r '.entries[] | "- \(.repo) @ \(.sha) (\(.commit_date))"' schemas/metadata.json
            echo
            echo "SHA256 (root):"
            cat merged.tl.sha256
            echo
            echo "See CHANGELOG.txt for unified diffs."
          } > RELEASE_BODY.txt

      - name: Create GitHub Release (if changed)
        if: steps.diff.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.title }}
          body_path: RELEASE_BODY.txt
          files: |
            merged.tl
            merged.tl.sha256

      - name: Upload artifacts (if changed)
        if: steps.diff.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: |
            merged.tl
            merged.tl.sha256
            schemas/latest.tl
            schemas/CHANGELOG.txt
            schemas/metadata.json
