name: Merge Telegram TL

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # 每6小时（UTC 00/06/12/18）

permissions:
  contents: write

concurrency:
  group: tl-merge
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run TL fetch & merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python fetch_and_merge_tl.py --outdir schemas

      - name: Detect changes
        id: diff
        run: |
          git add -N schemas/merged.tl schemas/merged.tl.sha256 || true
          if git diff --quiet -- schemas/merged.tl schemas/merged.tl.sha256; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi


      - name: Commit changes (if changed)
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(tl): 6-hourly update merged.tl [skip ci]"
          git push

      - name: Compose tag & release body (if changed)
        if: steps.diff.outputs.changed == 'true'
        id: tag
        run: |
          DT_UTC=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          DT_TAG=$(date -u +'%Y%m%d%H%M%S')
          SHA1=$(jq -r '.entries[0].sha' schemas/metadata.json | cut -c1-7)
          SHA2=$(jq -r '.entries[1].sha' schemas/metadata.json | cut -c1-7)
          echo "tag=tl-${DT_TAG}-${SHA1}-${SHA2}" >> $GITHUB_OUTPUT
          echo "title=TL Merge ${DT_UTC}" >> $GITHUB_OUTPUT
          {
            echo "Automated semantic merge of Telegram TL schemas."
            echo
            echo "Sources:"
            jq -r '.entries[] | "- \(.repo) @ \(.sha) (\(.commit_date))"' schemas/metadata.json
            echo
            echo "SHA256 (schemas/merged.tl):"
            cat schemas/merged.tl.sha256
            echo
            echo "See CHANGELOG.txt for unified diffs."
          } > RELEASE_BODY.txt

      - name: Create GitHub Release (if changed)
        if: steps.diff.outputs.changed == 'true'
        id: gh_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.title }}
          body_path: RELEASE_BODY.txt
          files: |
            schemas/merged.tl
            schemas/merged.tl.sha256

      - name: Notify Telegram (if changed)
        if: steps.diff.outputs.changed == 'true'
        env:
          TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_CHAT: ${{ secrets.TELEGRAM_CHAT_ID }}
          RELEASE_URL: ${{ steps.gh_release.outputs.html_url }}
        run: |
          if [ -z "$TG_TOKEN" ] || [ -z "$TG_CHAT" ]; then
            echo "Telegram secrets not set; skipping."
            exit 0
          fi
          {
            echo "TL schema updated ✅"
            echo "Tag: ${{ steps.tag.outputs.tag }}"
            echo "Release: ${RELEASE_URL}"
            echo
            echo "Sources:"
            jq -r '.entries[] | "- \(.repo) @ \(.sha) (\(.commit_date))"' schemas/metadata.json
            echo
            echo "SHA256 (schemas/merged.tl):"
            cat schemas/merged.tl.sha256
          } > msg.txt
          curl -sS "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            --data-urlencode chat_id="${TG_CHAT}" \
            --data-urlencode text@msg.txt

      - name: Upload artifacts (if changed)
        if: steps.diff.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: schemas
          path: |
            schemas/merged.tl
            schemas/merged.tl.sha256
            schemas/latest.tl
            schemas/CHANGELOG.txt
            schemas/metadata.json
